name: Docs Generator

on:
  push:
    paths:
      - 'README.md'
      - '.github/workflows/docs.yml'

jobs:
  generateDOC:
    name: Docs Generator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: technote-space/toc-generator@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAX_HEADER_LEVEL: 3
          FOLDING: false
      - name: Download mdsplit
        uses: carlosperate/download-file-action@v1.0.3
        id: download-mdsplit
        with:
          file-url: 'https://github.com/alandefreitas/mdsplit/releases/download/v0.0.1/Executable.Linux.zip'
          file-name: 'mdsplit.zip'
          location: '.'
      - name: Unzip mdsplit
        run: |
          unzip mdsplit.zip
          rm -f mdsplit.zip
          sudo chmod +x mdsplit
          ls
      - name: Generate Docs
        run: ./mdsplit -r RodolfoALopes/decomposition_library
      - uses: EndBug/add-and-commit@v5 # You can change this to use a specific version
        with:
          add: 'docs'
          author_name: GitHub Action[bot]
          author_email: action[bot]@github.com
          message: 'Update Docs'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
      - name: Push changes
        uses: ad-m/github-push-action@master
        if: ${{ success() }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true